# Destroys any cloud infrastructure that was deployed for the purpose of E2E testing.
name: Cloud infrastructure Cleanup

on:
  workflow_dispatch

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull aws-nuke image
        run: docker pull ghcr.io/ekristen/aws-nuke:v3.61.0

      - name: Run AWS Nuke
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            -e AWS_ACCESS_KEY_ID="${{ env.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ env.AWS_SECRET_ACCESS_KEY }}" \
            ghcr.io/ekristen/aws-nuke:v3.61.0 \
            run \
              --config ./.github/workflows/cleanup/aws-nuke-config.yml \
              --no-dry-run \
              --force \
              --force-sleep 3 \
              --max-wait-retries 100